version: "3"

services:
  app:
    image: node
    command: npm start
    ports:
      - "3001:3001"
    links:
      - db
    working_dir: /nodeApp
    environment:
      SEQ_DB: node-db-postgres
      SEQ_USER: postgres
      SEQ_PW: 123456
      PORT: 3001
      DATABASE_URL: postgres://postgres:123456@docker.for.mac.localhost/node-db-postgres
    volumes:
      - ./:/nodeApp
  db:
    image: postgres
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456