version: "3.7"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: node-db-postgre
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    image: node_app:latest
    command: npm start
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:123456@db:5432/node-db-postgre
      - PORT=3001
  