FROM node:8-slim

RUN mkdir /nodeApp
ADD . /nodeApp
WORKDIR /nodeApp

# Copy application to /nodeApp directory and install dependencies
COPY package.json /nodeApp
RUN npm install

# What should be executed when the Docker image is launching
CMD npm start

# Binds to port 3001
EXPOSE 3001

# Creates a mount point
VOLUME [ "/nodeApp" ]